# Generated by Django 5.1.4 on 2024-12-12 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_gasstationmodel_total'),
        ('users', '0002_rename_coordinates_usermodel_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasStationUserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gas_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_station_users', to='admins.gasstationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_station_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
