# Generated by Django 5.1.4 on 2024-12-11 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasstationmodel',
            old_name='location',
            new_name='point',
        ),
    ]
