# Generated by Django 5.1.4 on 2024-12-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_rename_location_gasstationmodel_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasstationmodel',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
