# Generated by Django 5.1.4 on 2024-12-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_gasstationmodel_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasstationmodel',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gasstationmodel',
            name='comment_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
