# Generated by Django 5.1.4 on 2024-12-14 19:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_gasstationmodel_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstationmodel',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=3857),
        ),
    ]
