# Generated by Django 5.1.4 on 2024-12-14 19:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_gasstationmodel_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstationmodel',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
