# Generated by Django 5.1.4 on 2024-12-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_gasstationmodel_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasstationmodel',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasstationmodel',
            name='is_open_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
